# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c05c88a5eb2f5826a69e708b54ab0d56b7870b70933c86d884ad205df174e0b941c0fc2b5dc142686f36d23a745cbd754ae8d89ac52511d98403c89cfb931fa

test:
  secret_key_base: 1fd7bd00bdaf7536518159553f2b9565e7a12c6d180436be1a049b07a35786fa9e1a92c0b38122482feaa6036550e1691cb68cd583d23dbfdab34fb95192bc3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
